import type { NextPage } from "next";
import Head from "next/head";
import CallToAction from "../components/callToAction";
import Cards from "../components/cards";
import ConceptExplanation from "../components/conceptExplanation";
import Hero from "../components/hero";
import Pricing from "../components/pricing";
import ProfileCard from "../components/profileCard";
import SvgTransition from "../components/svgTransition";

const Home: NextPage = () => {
  return (
    <main className="leading-normal tracking-normal text-white gradient">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <SvgTransition version={1} />
      <ConceptExplanation />
      <ProfileCard />
      {/* <Cards />
      <Pricing /> */}
      {/* <SvgTransition version={2} /> */}
      {/* <CallToAction /> */}
    </main>
  );
};

export default Home;
